name: CMake Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          chmod +x ./setup.sh
          ./setup.sh

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Set LLVM_DIR
        run: |
          echo "LLVM_DIR=/usr/lib/llvm-15/lib/cmake/llvm" >> $GITHUB_ENV

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh -DCMAKE_PREFIX_PATH="$LLVM_DIR" -DCMAKE_BUILD_TYPE=Release -DUSE_LLD=ON

      - name: Run tests
        run: |
          chmod +x ./test.sh
          ./test.sh

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: build/